#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json
test_format = 1.0

[default]

    exclude = [ "install.nourl" ]

    test_upgrade_from.0dc87d96.name = "Upgrade from 2.2.0"
