#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression --message="Updating NGINX web server configuration..." --weight=1

ynh_change_url_nginx_config

#=================================================
# REBUILD CINNY
#=================================================
ynh_script_progression --message="Rebuilding $app..." --weight=1

cp "$install_dir/www/config.json" "$install_dir/config.json"

_patch_build_config "$install_dir/source"
_npm_build_install "$install_dir/source" "$install_dir/www"

mv "$install_dir/config.json" "$install_dir/www/config.json"

# Fix any permissions in the install dir
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Change of URL completed for $app" --last
