#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# CHANGE HARDCODED URLS IN APP FILES
#=================================================

# Prepare var for string replacement (empty if $path is root or $path if subdir is defined)
old_path_2=""
if [[ $old_path != '/' ]]; then old_path_2=$old_path; fi
new_path_2=""
if [[ $new_path != '/' ]]; then new_path_2=$new_path; fi

# Replace base URL recursively in all files of the app folder
match_regex="$old_domain$old_path_2"
grep --extended-regexp --recursive --files-with-matches --ignore-case "$match_regex" $install_dir/* | xargs -d '\n' sed --regexp-extended --in-place "s@$match_regex@$new_domain$new_path_2@g"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
