#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir" --source_id="ynh_build"

#Prepare $newpath for string replacement (empty if $path is root or $path if subdir is defined)
newpath=""
if [[ $path != '/' ]]; then newpath=$path; fi

# Replace path placeholder recursively in all files of the app folder
#grep -rli '/__YNH_SUBDIR_PATH__' $install_dir/* | xargs sed -i "s@/__YNH_SUBDIR_PATH__@https://$domain$newpath@g"
grep -rli '/__YNH_SUBDIR_PATH__' $install_dir/* | xargs sed -i "s@/__YNH_SUBDIR_PATH__@\.@g"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

ynh_config_add_nginx

#=================================================
# CINNY CONFIGURATION
#=================================================
ynh_script_progression "Configuring Cinny..."

ynh_config_add --template="cinny.json" --destination="$install_dir/config.json"
chmod 640 "$install_dir/config.json"
chown "$app:www-data" "$install_dir/config.json"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
