#!/bin/bash


source /usr/share/yunohost/helpers

if [[ "$path" != "/" ]]; then
    ynh_die "Installing Cinny on a subpath is not supported anymore (see https://github.com/YunoHost-Apps/cinny_ynh/pull/66)"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="config.json"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Upgrading NGINX web server configuration..."

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
